import { Router, Response } from 'express';
import crypto from 'crypto';
import { authenticate, authorize, AuthRequest } from '../middleware/auth';
import prisma from '../lib/prisma';

const router = Router();
const id = () => crypto.randomUUID();
const enc = (v: unknown) => JSON.stringify(v ?? {});
const dec = (v: unknown, fallback: any = {}) => { try { return v ? JSON.parse(String(v)) : fallback; } catch { return fallback; } };

async function workspace(req: AuthRequest, res: Response) {
  const workspaceId = String(req.headers['x-workspace-id'] || req.body?.workspaceId || req.query.workspaceId || '');
  if (!workspaceId) { res.status(400).json({ error: 'x-workspace-id is required' }); return null; }
  const rows = await prisma.$queryRawUnsafe<any[]>('SELECT * FROM workspace_members WHERE workspace_id=? AND user_id=? AND status=? LIMIT 1', workspaceId, req.user!.userId, 'active');
  if (!rows[0]) { res.status(403).json({ error: 'Workspace access denied' }); return null; }
  return workspaceId;
}

router.post('/bootstrap', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const existing = await prisma.$queryRawUnsafe<any[]>('SELECT w.*,m.role FROM workspaces w JOIN workspace_members m ON m.workspace_id=w.id WHERE m.user_id=? LIMIT 1', req.user!.userId);
    if (existing[0]) return res.json({ workspace: existing[0], created: false });
    const wid=id(), name=String(req.body?.name||'My Workspace').slice(0,120), slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)}-${wid.slice(0,8)}`;
    await prisma.$transaction(async tx=>{ await tx.$executeRawUnsafe('INSERT INTO workspaces (id,name,slug) VALUES (?,?,?)',wid,name,slug); await tx.$executeRawUnsafe('INSERT INTO workspace_members (id,workspace_id,user_id,role) VALUES (?,?,?,?)',id(),wid,req.user!.userId,'owner'); await tx.$executeRawUnsafe('INSERT INTO crm_roles (id,workspace_id,name,description,permissions) VALUES (?,?,?,?,?)',id(),wid,'Owner','Full workspace access',enc(['*'])); });
    res.status(201).json({ workspace:(await prisma.$queryRawUnsafe<any[]>('SELECT * FROM workspaces WHERE id=?',wid))[0], created:true });
  } catch (e) { console.error(e); res.status(500).json({error:'Failed to bootstrap workspace'}); }
});
router.get('/workspaces',authenticate,async(req:AuthRequest,res:Response)=>res.json(await prisma.$queryRawUnsafe<any[]>('SELECT w.*,m.role,m.status AS member_status FROM workspaces w JOIN workspace_members m ON m.workspace_id=w.id WHERE m.user_id=? ORDER BY w.name',req.user!.userId)));
router.get('/members',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;res.json(await prisma.$queryRawUnsafe<any[]>('SELECT m.id,m.role,m.status,u.id AS user_id,u.name,u.email,u.avatar FROM workspace_members m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=? ORDER BY u.name',ws));});
router.post('/members',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const email=String(req.body?.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'email is required'});const users=await prisma.$queryRawUnsafe<any[]>('SELECT id,name,email FROM users WHERE lower(email)=? LIMIT 1',email);if(!users[0])return res.status(404).json({error:'User not found'});await prisma.$executeRawUnsafe('INSERT OR IGNORE INTO workspace_members (id,workspace_id,user_id,role) VALUES (?,?,?,?)',id(),ws,users[0].id,String(req.body.role||'member'));res.status(201).json({user:users[0],role:String(req.body.role||'member')});});

router.get('/companies',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const q=String(req.query.q||'').trim();const rows=q?await prisma.$queryRawUnsafe<any[]>('SELECT * FROM companies WHERE workspace_id=? AND (name LIKE ? OR email LIKE ? OR domain LIKE ?) ORDER BY name LIMIT 200',ws,`%${q}%`,`%${q}%`,`%${q}%`):await prisma.$queryRawUnsafe<any[]>('SELECT * FROM companies WHERE workspace_id=? ORDER BY updated_at DESC LIMIT 200',ws);res.json(rows.map(r=>({...r,metadata:dec(r.metadata)})));});
router.post('/companies',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.name)return res.status(400).json({error:'name is required'});const cid=id();await prisma.$executeRawUnsafe('INSERT INTO companies (id,workspace_id,name,domain,industry,phone,email,website,address,status,owner_id,metadata) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',cid,ws,b.name,b.domain||null,b.industry||null,b.phone||null,b.email||null,b.website||null,b.address||null,b.status||'active',req.user!.userId,enc(b.metadata));res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM companies WHERE id=?',cid))[0]);});
router.put('/companies/:id',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{},map:any={name:'name',domain:'domain',industry:'industry',phone:'phone',email:'email',website:'website',address:'address',status:'status',metadata:'metadata'},keys=Object.keys(map).filter(k=>b[k]!==undefined);if(!keys.length)return res.status(400).json({error:'No fields to update'});const vals=keys.map(k=>k==='metadata'?enc(b[k]):b[k]);await prisma.$executeRawUnsafe(`UPDATE companies SET ${keys.map(k=>`${map[k]}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?`,...vals,req.params.id,ws);res.json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM companies WHERE id=? AND workspace_id=?',req.params.id,ws))[0]||null);});
router.delete('/companies/:id',authenticate,authorize('ADMIN','MANAGER','SYSTEM_OWNER'),async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;await prisma.$executeRawUnsafe('DELETE FROM companies WHERE id=? AND workspace_id=?',req.params.id,ws);res.status(204).send();});

router.get('/people',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const q=String(req.query.q||'').trim();const rows=q?await prisma.$queryRawUnsafe<any[]>('SELECT p.*,c.name AS company_name FROM people p LEFT JOIN companies c ON c.id=p.company_id WHERE p.workspace_id=? AND (p.first_name LIKE ? OR p.last_name LIKE ? OR p.email LIKE ? OR c.name LIKE ?) ORDER BY p.updated_at DESC LIMIT 300',ws,`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`):await prisma.$queryRawUnsafe<any[]>('SELECT p.*,c.name AS company_name FROM people p LEFT JOIN companies c ON c.id=p.company_id WHERE p.workspace_id=? ORDER BY p.updated_at DESC LIMIT 300',ws);res.json(rows);});
router.post('/people',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.firstName)return res.status(400).json({error:'firstName is required'});const pid=id();await prisma.$executeRawUnsafe('INSERT INTO people (id,workspace_id,company_id,first_name,last_name,email,phone,job_title,linkedin_url,status,owner_id,metadata) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',pid,ws,b.companyId||null,b.firstName,b.lastName||null,b.email||null,b.phone||null,b.jobTitle||null,b.linkedinUrl||null,b.status||'active',req.user!.userId,enc(b.metadata));res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM people WHERE id=?',pid))[0]);});
router.put('/people/:id',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{},map:any={firstName:'first_name',lastName:'last_name',companyId:'company_id',email:'email',phone:'phone',jobTitle:'job_title',linkedinUrl:'linkedin_url',status:'status',metadata:'metadata'},keys=Object.keys(map).filter(k=>b[k]!==undefined);if(!keys.length)return res.status(400).json({error:'No fields to update'});const vals=keys.map(k=>k==='metadata'?enc(b[k]):b[k]);await prisma.$executeRawUnsafe(`UPDATE people SET ${keys.map(k=>`${map[k]}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?`,...vals,req.params.id,ws);res.json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM people WHERE id=? AND workspace_id=?',req.params.id,ws))[0]||null);});
router.delete('/people/:id',authenticate,authorize('ADMIN','MANAGER','SYSTEM_OWNER'),async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;await prisma.$executeRawUnsafe('DELETE FROM people WHERE id=? AND workspace_id=?',req.params.id,ws);res.status(204).send();});

router.get('/opportunities',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const rows=await prisma.$queryRawUnsafe<any[]>('SELECT o.*,c.name AS company_name,p.first_name AS contact_first_name,p.last_name AS contact_last_name,u.name AS owner_name FROM opportunities o LEFT JOIN companies c ON c.id=o.company_id LEFT JOIN people p ON p.id=o.primary_person_id LEFT JOIN users u ON u.id=o.owner_id WHERE o.workspace_id=? ORDER BY o.updated_at DESC LIMIT 500',ws);res.json(rows);});
router.post('/opportunities',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.name)return res.status(400).json({error:'name is required'});const oid=id();await prisma.$executeRawUnsafe('INSERT INTO opportunities (id,workspace_id,company_id,primary_person_id,name,amount,stage,probability,expected_close_date,owner_id,source,description,metadata) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',oid,ws,b.companyId||null,b.primaryPersonId||null,b.name,Number(b.amount||0),b.stage||'INTAKE',Math.max(0,Math.min(100,Number(b.probability??10))),b.expectedCloseDate||null,b.ownerId||req.user!.userId,b.source||null,b.description||null,enc(b.metadata));res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM opportunities WHERE id=?',oid))[0]);});
router.patch('/opportunities/:id',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{},map:any={name:'name',amount:'amount',stage:'stage',probability:'probability',expectedCloseDate:'expected_close_date',companyId:'company_id',primaryPersonId:'primary_person_id',ownerId:'owner_id',source:'source',description:'description',metadata:'metadata'},keys=Object.keys(map).filter(k=>b[k]!==undefined);if(!keys.length)return res.status(400).json({error:'No fields to update'});const vals=keys.map(k=>k==='metadata'?enc(b[k]):b[k]);await prisma.$executeRawUnsafe(`UPDATE opportunities SET ${keys.map(k=>`${map[k]}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?`,...vals,req.params.id,ws);res.json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM opportunities WHERE id=? AND workspace_id=?',req.params.id,ws))[0]||null);});

router.get('/notes',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const et=String(req.query.entityType||''),eid=String(req.query.entityId||'');const rows=et&&eid?await prisma.$queryRawUnsafe<any[]>('SELECT n.*,u.name AS author_name FROM crm_notes n LEFT JOIN users u ON u.id=n.author_id WHERE n.workspace_id=? AND n.entity_type=? AND n.entity_id=? ORDER BY n.created_at DESC',ws,et,eid):await prisma.$queryRawUnsafe<any[]>('SELECT n.*,u.name AS author_name FROM crm_notes n LEFT JOIN users u ON u.id=n.author_id WHERE n.workspace_id=? ORDER BY n.created_at DESC LIMIT 200',ws);res.json(rows);});
router.post('/notes',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.entityType||!b.entityId||!b.body)return res.status(400).json({error:'entityType, entityId and body are required'});const nid=id();await prisma.$executeRawUnsafe('INSERT INTO crm_notes (id,workspace_id,entity_type,entity_id,body,author_id) VALUES (?,?,?,?,?,?)',nid,ws,b.entityType,b.entityId,b.body,req.user!.userId);res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM crm_notes WHERE id=?',nid))[0]);});
router.get('/custom-fields',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const et=String(req.query.entityType||'');const rows=await prisma.$queryRawUnsafe<any[]>('SELECT * FROM custom_field_definitions WHERE workspace_id=? AND (?="" OR entity_type=?) ORDER BY name',ws,et,et);res.json(rows.map(r=>({...r,options:dec(r.options,[]),required:Boolean(r.required)})));});
router.post('/custom-fields',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.entityType||!b.name||!b.key)return res.status(400).json({error:'entityType, name and key are required'});const fid=id();await prisma.$executeRawUnsafe('INSERT INTO custom_field_definitions (id,workspace_id,entity_type,name,key,field_type,options,required) VALUES (?,?,?,?,?,?,?,?)',fid,ws,b.entityType,b.name,b.key,b.fieldType||'text',enc(b.options||[]),b.required?1:0);res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM custom_field_definitions WHERE id=?',fid))[0]);});
router.put('/custom-fields/:id/value',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const defs=await prisma.$queryRawUnsafe<any[]>('SELECT id FROM custom_field_definitions WHERE id=? AND workspace_id=?',req.params.id,ws);if(!defs[0])return res.status(404).json({error:'Field not found'});await prisma.$executeRawUnsafe('INSERT INTO custom_field_values (id,definition_id,entity_id,value) VALUES (?,?,?,?) ON CONFLICT(definition_id,entity_id) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP',id(),req.params.id,String(req.body.entityId),req.body.value==null?null:String(req.body.value));res.json({success:true});});
router.get('/views',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const et=String(req.query.entityType||'');const rows=await prisma.$queryRawUnsafe<any[]>('SELECT * FROM saved_views WHERE workspace_id=? AND (?="" OR entity_type=?) ORDER BY name',ws,et,et);res.json(rows.map(r=>({...r,filters:dec(r.filters),columns:dec(r.columns,[]),isShared:Boolean(r.is_shared)})));});
router.post('/views',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.entityType||!b.name)return res.status(400).json({error:'entityType and name are required'});const vid=id();await prisma.$executeRawUnsafe('INSERT INTO saved_views (id,workspace_id,entity_type,name,filters,columns,sort,is_shared,owner_id) VALUES (?,?,?,?,?,?,?,?,?)',vid,ws,b.entityType,b.name,enc(b.filters||{}),enc(b.columns||[]),b.sort||null,b.isShared?1:0,req.user!.userId);res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM saved_views WHERE id=?',vid))[0]);});
router.delete('/views/:id',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;await prisma.$executeRawUnsafe('DELETE FROM saved_views WHERE id=? AND workspace_id=?',req.params.id,ws);res.status(204).send();});
router.get('/search',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const q=`%${String(req.query.q||'').trim()}%`;if(q==='%%')return res.json({companies:[],people:[],opportunities:[],leads:[],clients:[]});const [companies,people,opportunities,leads,clients]=await Promise.all([prisma.$queryRawUnsafe<any[]>('SELECT id,name,domain FROM companies WHERE workspace_id=? AND name LIKE ? LIMIT 25',ws,q),prisma.$queryRawUnsafe<any[]>('SELECT id,first_name,last_name,email,company_id FROM people WHERE workspace_id=? AND (first_name LIKE ? OR last_name LIKE ? OR email LIKE ?) LIMIT 25',ws,q,q,q),prisma.$queryRawUnsafe<any[]>('SELECT id,name,amount,stage,company_id FROM opportunities WHERE workspace_id=? AND name LIKE ? LIMIT 25',ws,q),prisma.$queryRawUnsafe<any[]>('SELECT id,name,company,value,stage FROM leads WHERE name LIKE ? OR company LIKE ? LIMIT 25',q,q),prisma.$queryRawUnsafe<any[]>('SELECT id,name,company,email,total_revenue FROM clients WHERE name LIKE ? OR company LIKE ? LIMIT 25',q,q)]);res.json({companies,people,opportunities,leads,clients});});
router.get('/roles',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const rows=await prisma.$queryRawUnsafe<any[]>('SELECT * FROM crm_roles WHERE workspace_id=? ORDER BY name',ws);res.json(rows.map(r=>({...r,permissions:dec(r.permissions,[])})));});
router.post('/roles',authenticate,authorize('ADMIN','MANAGER','SYSTEM_OWNER'),async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};if(!b.name)return res.status(400).json({error:'name is required'});const rid=id();await prisma.$executeRawUnsafe('INSERT INTO crm_roles (id,workspace_id,name,description,permissions) VALUES (?,?,?,?,?)',rid,ws,b.name,b.description||null,enc(b.permissions||[]));res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM crm_roles WHERE id=?',rid))[0]);});
router.put('/roles/:id',authenticate,authorize('ADMIN','MANAGER','SYSTEM_OWNER'),async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const b=req.body||{};await prisma.$executeRawUnsafe('UPDATE crm_roles SET name=COALESCE(?,name),description=COALESCE(?,description),permissions=COALESCE(?,permissions),updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?',b.name||null,b.description||null,b.permissions===undefined?null:enc(b.permissions),req.params.id,ws);res.json({success:true});});
router.get('/export/:entity',authenticate,async(req:AuthRequest,res:Response)=>{const ws=await workspace(req,res);if(!ws)return;const table:any={companies:'companies',people:'people',opportunities:'opportunities'}[String(req.params.entity)];if(!table)return res.status(400).json({error:'Unsupported export entity'});const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM ${table} WHERE workspace_id=? ORDER BY updated_at DESC`,ws);const keys=rows.length?Object.keys(rows[0]):[];const quote=(v:any)=>`"${String(v??'').replace(/"/g,'""').replace(/\n/g,' ')}"`;const csv=[keys.join(','),...rows.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\n');res.type('text/csv').setHeader('Content-Disposition',`attachment; filename="${req.params.entity}.csv"`).send(csv);});

export default router;
