import { Router } from 'express';
import crypto from 'crypto';
import { authenticate, AuthRequest } from '../middleware/auth';
import prisma from '../lib/prisma';
const router=Router();
const ws=(req:AuthRequest)=>String(req.headers['x-workspace-id']||req.query.workspaceId||req.body?.workspaceId||'');
async function ok(req:AuthRequest,w:string){if(!w||!req.user)return false;const r=await prisma.$queryRawUnsafe<any[]>('SELECT id FROM workspace_members WHERE workspace_id=? AND user_id=? AND status=? LIMIT 1',w,req.user.userId,'active');return !!r[0];}
router.get('/search',authenticate,async(req:AuthRequest,res)=>{const w=ws(req);if(!await ok(req,w))return res.status(403).json({error:'Workspace access denied'});const q=`%${String(req.query.q||'').trim()}%`;if(q==='%%')return res.json([]);const [c,p,o]=await Promise.all([prisma.$queryRawUnsafe<any[]>('SELECT id,name,email,domain,\'company\' type FROM companies WHERE workspace_id=? AND (name LIKE ? OR email LIKE ? OR domain LIKE ?) LIMIT 20',w,q,q,q),prisma.$queryRawUnsafe<any[]>('SELECT id,first_name,last_name,email,\'person\' type FROM people WHERE workspace_id=? AND (first_name LIKE ? OR last_name LIKE ? OR email LIKE ?) LIMIT 20',w,q,q,q),prisma.$queryRawUnsafe<any[]>('SELECT id,name,amount,stage,\'opportunity\' type FROM opportunities WHERE workspace_id=? AND name LIKE ? LIMIT 20',w,q)]);res.json([...c,...p,...o]);});
router.get('/views',authenticate,async(req:AuthRequest,res)=>{const w=ws(req);if(!await ok(req,w))return res.status(403).json({error:'Workspace access denied'});res.json(await prisma.$queryRawUnsafe<any[]>('SELECT * FROM crm_saved_views WHERE workspace_id=? ORDER BY name',w));});
router.post('/views',authenticate,async(req:AuthRequest,res)=>{const w=ws(req);if(!await ok(req,w))return res.status(403).json({error:'Workspace access denied'});const b=req.body||{};if(!b.name||!b.entityType)return res.status(400).json({error:'name and entityType are required'});const id=crypto.randomUUID();await prisma.$executeRawUnsafe('INSERT INTO crm_saved_views (id,workspace_id,name,entity_type,filters,columns,sort,created_by) VALUES (?,?,?,?,?,?,?,?)',id,w,b.name,b.entityType,JSON.stringify(b.filters||{}),JSON.stringify(b.columns||[]),JSON.stringify(b.sort||{}),req.user!.userId);res.status(201).json((await prisma.$queryRawUnsafe<any[]>('SELECT * FROM crm_saved_views WHERE id=?',id))[0]);});
router.get('/export/:entity',authenticate,async(req:AuthRequest,res)=>{const w=ws(req);if(!await ok(req,w))return res.status(403).json({error:'Workspace access denied'});let rows:any[]=[];const e=String(req.params.entity);if(e==='companies')rows=await prisma.$queryRawUnsafe<any[]>('SELECT id,name,domain,industry,phone,email,website,address,status,owner_id FROM companies WHERE workspace_id=? ORDER BY name',w);else if(e==='people')rows=await prisma.$queryRawUnsafe<any[]>('SELECT id,first_name,last_name,email,phone,job_title,company_id,status,owner_id FROM people WHERE workspace_id=? ORDER BY last_name,first_name',w);else if(e==='opportunities')rows=await prisma.$queryRawUnsafe<any[]>('SELECT id,name,amount,stage,probability,expected_close_date,company_id,primary_person_id,owner_id,source,status FROM opportunities WHERE workspace_id=? ORDER BY updated_at DESC',w);else return res.status(400).json({error:'Unsupported export entity'});const keys=rows.length?Object.keys(rows[0]):[];const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');res.type('text/csv').set('Content-Disposition',`attachment; filename="amplify-${e}.csv"`).send(csv);});
export default router;
